### ISSUE TITLE
User requested software installation on their JupyterHub instance

### ISSUE THREAD

**Issue by KCB13** [heliumplusdatastage/COPDGene#2]
User: Phuwanat Sakomsakolpat

**Comment by KCB13** [comment]
@muralikarthikk please let me know 1) what software Phuwanat needs installed 2) ETA to complete the installation.

**Comment by muralikarthikk** [comment]
@KCB13 I did not hear back from Phuwanat. Installing the packages does not take much time (few minutes). Please let me know the packages which he needs be installed.

**Comment by KCB13** [comment]
Murali added the following on 11/2:

- PyVCF (https://pyvcf.readthedocs.io/en/latest/INTRO.html)
- Kipoi (http://kipoi.org/)
